import { type BBox, type LngLat, bboxBuffer, bboxContains } from './geo';

/**
 * Bounding box of the Italian Republic including its islands, the enclaved
 * states (San Marino, Vatican City) and the Campione d'Italia exclave.
 *
 * This is a coarse pre-filter only. The authoritative coverage test is the
 * polygon in `data/coverage.geojson`, generated by the pipeline from OSM
 * `admin_level=2` boundaries (SPEC §1.0, §3.1 step 2). Anything that must be
 * exact — gateway coverage checks, the render mask — uses that polygon; this
 * bbox exists to reject obvious outliers without loading geometry.
 *
 * Extremes it must contain:
 *   N Vetta d'Italia ~47.09   S Isola di Lampedusa ~35.49
 *   W Rocca Bernauda ~6.63    E Capo d'Otranto     ~18.52
 */
export const ITALY_BBOX: BBox = [6.6, 35.29, 18.8, 47.1];

/** Margin added to the coverage bbox to obtain the map's `maxBounds` (SPEC §1.0). */
export const MAX_BOUNDS_MARGIN_M = 50_000;

/** Map `maxBounds`: the coverage bbox plus roughly 50 km on every side. */
export const ITALY_MAX_BOUNDS: BBox = bboxBuffer(ITALY_BBOX, MAX_BOUNDS_MARGIN_M);

/**
 * Development area: Val Gardena / Val di Fassa / Sella group (SPEC §3.0).
 * Dense in CAI trails, via ferrate, rifugi, pistes, lifts and trilingual names,
 * which makes it the cheapest area that still exercises every layer.
 */
export const DEV_BBOX: BBox = [11.55, 46.35, 11.95, 46.65];

/** Areas the pipeline can build. */
export const AREAS = ['dev', 'italy'] as const;
export type Area = (typeof AREAS)[number];

export function isArea(value: string): value is Area {
  return (AREAS as readonly string[]).includes(value);
}

export function bboxForArea(area: Area): BBox {
  return area === 'dev' ? DEV_BBOX : ITALY_BBOX;
}

/** Coarse bbox pre-filter. A `true` result still needs the polygon check. */
export function isPlausiblyInsideCoverage(point: LngLat): boolean {
  return bboxContains(ITALY_BBOX, point);
}

/** Error code the gateway returns for out-of-coverage input (SPEC §1.0). */
export const OUT_OF_COVERAGE = 'OUT_OF_COVERAGE' as const;
